services:
  postgres-db: 
    image: postgres:latest  # Utilise la dernière version de PostgreSQL
    container_name: windturbinepower # Nom du conteneur
    restart: "no" # Ne redémarre pas le conteneur automatiquement
    environment:  # Variables d'environnement pour la configuration de PostgreSQL
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432" # Mapping du port 5432 du conteneur vers le port 5433 de l'hôte
    volumes:
      - windturbinepower-data:/var/lib/postgresql # Chemin vers le volume pgdata dans lequel vont être persisté nos données
    networks:
      - windturbinepower-network
  bronze:  # Service d'ingestion (extraction et chargement dans la couche Bronze)
    image: bronze
    restart: "no"
    depends_on:
      - postgres-db
    env_file: # Utilisation d'un fichier d'environnement pour les variables sensibles
      - etl.env
    environment:
      # Date d'ingestion (peut être surchargée en ligne de commande)
      INGEST_JOUR: ${INGEST_JOUR:-15}
      INGEST_MOIS: ${INGEST_MOIS:-6}
      INGEST_ANNEE: ${INGEST_ANNEE:-2024}
    networks:
      - windturbinepower-network

networks:
  windturbinepower-network:
    name: windturbinepower-network # force le nom exact 
    driver: bridge
volumes:
  windturbinepower-data:
